// function Differenzzeitmessung
// Generated by Structorizer 3.31-02

#include <stdbool.h>
#define USEC_IN_NANOSEC 1000;
#define SLEEPING_FACTOR 1000;
#define ITERATIONS 100;
#define SLEEPING 3000;

// TODO: Revise the return type and declare the parameters.
void Differenzzeitmessung(void)
{
	// TODO: Check and accomplish variable declarations:
	int i;
	struct timespec start_sleep;
	struct timespec end_sleep;
	struct timespec timestamp;
	struct timespec result_sleep;
	struct timespec difference_sleep;
	time_t results_list[ITERATIONS];
	if (i > 100)
	{
		Min(results_list);
		Mittelwert(results_list);
		Max(results_list);
	}
	else
	{
		for (i = 1; i <= 100; i += (1))
			time_t sleeping_time = SLEEPING * USEC_IN_NANOSEC;
		{
			time.tv_sec = 0;
			time.tv_nsec = sleeping_time;
			clock_gettime(CLOCK_MONOTONIC, &start_sleep);
			clock_nanosleep(CLOCK_MONOTONIC, 0, &time, NULL);
			clock_gettime(CLOCK_MONOTONIC, &end_sleep);
			Difftime(&start_sleep, &end_sleep, &result_sleep);
			difference_sleep.tv_nsec = (result_sleep.tv_nsec - sleeping_time);
			results_list[i - 1] = difference_sleep.tv_nsec;
		}
	}
}
