// function copy_file(const char *const infilename, const char *const outfilename, const int bufsize) 
// Generated by Structorizer 3.31-02 

#include <stdbool.h>


int copy_file(const char *const infilename, const char *const outfilename, const int bufsize)
{
    char *buffer;
    int out;
    int in;
    int count_read;
    int count_write;
    if (infilename == NULL || outfilename == NULL)
    {
        perror("Wrong Parameter");
        return 0;
    } else
    {
        in = open(infilename, O_RDONLY);
        if (in < 0)
        {
            perror(infilename);
            return -1;
        } else
        {
            out = open(outfilename, O_WRONLY | O_CREAT | O_TRUNC, 0644);
            if (out < 0)
            {
                perror(outfilename);
                return -1;
            } else
            {
                buffer = (char *) malloc(bufsize);
                if (buffer == NULL)
                {
                    perror("Malloc mistake");
                    goto failed_action;
                } else
                {
                    do
                    {
                        count_read = read(in, buffer, bufsize);
                        if (count_read == -1)
                        {
                            perror("Read failed");
                            goto failed_action;
                        } else
                        {
                            count_write == write(out, buffer, count);
                            if (count_write == -1)
                            {
                                perror("Write failed");
                                goto failed_action;
                            }
                        }
                    } while (count);
                    free(buffer);
                    close(in);
                    close(out);
                }
            }
        }
    }

    return 0;
}
